// <auto-generated />
using MessedUpSearchA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessedUpSearchA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617155110_MakeScLinkNullable")]
    partial class MakeScLinkNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MessedUpSearchA.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiGenreTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrmStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IgLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRedFlagged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastParsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTrackDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinktreeLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPlays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScLink")
                        .IsUnique()
                        .HasFilter("\"ScLink\" IS NOT NULL");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MessedUpSearchA.Models.Beat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Added")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Bpm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("MessedUpSearchA.Models.SentBeatsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BeatId");

                    b.ToTable("SentBeatsLog");
                });

            modelBuilder.Entity("MessedUpSearchA.Models.SentBeatsLog", b =>
                {
                    b.HasOne("MessedUpSearchA.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessedUpSearchA.Models.Beat", "Beat")
                        .WithMany()
                        .HasForeignKey("BeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Beat");
                });
#pragma warning restore 612, 618
        }
    }
}
