using System.Collections.Generic;

namespace MessedUpSearchA.Services.Localization;

/// <summary>
/// Сами строки. Английский — база: если ключа нет в русском, покажется английский,
/// а не пустота. Ключи именуются «экран.элемент», чтобы искать было по чему.
///
/// Сюда не попадают данные: названия жанров, статусы битов (POTENTIAL/FREE/SOLD),
/// CRM-статусы и содержимое фейкового превью. Это значения, а не подписи — они
/// хранятся в базе и от языка интерфейса не зависят.
/// </summary>
public static class LocalizationStrings
{
    public static readonly Dictionary<string, string> English = new()
    {
        // Главное окно
        ["Tabs.Beats"] = "BEATS BASE",
        ["Tabs.Artists"] = "ARTISTS",
        ["Status.Artists"] = "Artists:",
        ["Status.Beats"] = "Beats:",
        ["Status.Parser"] = "PARSER: {0}",
        ["Parser.Idle"] = "Idle",

        // Кнопки на панелях
        ["Buttons.AddBeat"] = "+ ADD BEAT",
        ["Buttons.ImportFolder"] = "IMPORT FOLDER",
        ["Buttons.AddArtist"] = "+ ADD ARTIST",
        ["Buttons.Parser"] = "⌕ PARSER",
        ["Buttons.Crm"] = "CRM",
        ["Buttons.Settings"] = "SETTINGS",
        ["Buttons.Save"] = "SAVE",
        ["Buttons.Cancel"] = "CANCEL",
        ["Buttons.Delete"] = "DELETE",
        ["Buttons.Close"] = "CLOSE",

        // Таблица битов
        ["Beats.Name"] = "BEAT NAME",
        ["Beats.Genre"] = "TYPE / GENRE",
        ["Beats.Bpm"] = "BPM",
        ["Beats.Key"] = "KEY",
        ["Beats.Added"] = "ADDED",
        ["Beats.Status"] = "STATUS",
        ["Beats.Empty"] = "EXAMPLE — your beats will appear here. Press + ADD BEAT",

        // Таблица артистов
        ["Artists.Nickname"] = "NICKNAME",
        ["Artists.Genre"] = "TYPE / GENRE",
        ["Artists.Plays"] = "PLAYS\n(total)",
        ["Artists.Links"] = "Links to social media and music platforms",
        ["Artists.Language"] = "LANGUAGE",
        ["Artists.Empty"] = "EXAMPLE — your artists will appear here. Press + ADD ARTIST",

        // Фильтры
        ["Filter.Type"] = "TYPE",
        ["Filter.Key"] = "KEY",
        ["Filter.Period"] = "PERIOD",
        ["Filter.Plays"] = "PLAYS",
        ["Filter.Language"] = "LANGUAGE",
        ["Filter.Search"] = "SEARCH (KEY WORD)",
        ["Filter.Min"] = "min",
        ["Filter.Max"] = "max",

        // Карточка бита
        ["BeatEditor.Add"] = "ADD BEAT",
        ["BeatEditor.Edit"] = "EDIT BEAT",
        ["BeatEditor.License"] = "LICENSE (IF SOLD)",
        ["BeatEditor.AssignArtists"] = "ASSIGN TO ARTISTS",
        ["BeatEditor.Similar"] = "SIMILAR ARTISTS",
        ["BeatEditor.Analyze"] = "ANALYZE",
        ["BeatEditor.Stop"] = "STOP",
        ["BeatEditor.SimilarHint"] = "Press ANALYZE — we'll find artists whose sound your beat resembles",

        // Карточка артиста
        ["ArtistEditor.Add"] = "ADD ARTIST",
        ["ArtistEditor.Edit"] = "EDIT ARTIST",
        ["ArtistEditor.ScLink"] = "SOUNDCLOUD LINK",
        ["ArtistEditor.Instagram"] = "INSTAGRAM",
        ["ArtistEditor.Spotify"] = "SPOTIFY",
        ["ArtistEditor.CrmStatus"] = "CRM STATUS",
        ["ArtistEditor.Notes"] = "NOTES",
        ["ArtistEditor.AssignedBeats"] = "ASSIGNED BEATS",
        ["ArtistEditor.NoneHint"] = "(can be empty)",
        ["ArtistEditor.LanguageHint"] = "ENG / RU / ...",
        ["ArtistEditor.MatchingBeats"] = "BEATS THAT FIT",
        ["ArtistEditor.NoMatches"] = "No beat matched this artist yet. Analyze your beats on their cards — matching ones will show up here.",
        ["ArtistEditor.UnknownArtist"] = "The model doesn't know this artist: it was trained on 32 specific ones, and matching goes by name. For everyone else this block stays empty.",
        ["ArtistEditor.NoModel"] = "Artist database file is missing — matching is unavailable.",

        // Анализ похожести (сообщения из кода)
        ["Analysis.NoFile"] = "Beat file not found — nothing to analyze",
        ["Analysis.NoIndex"] = "Artist database file is missing (artist_index.bin)",
        ["Analysis.Downloading"] = "Downloading the model (208 MB, one time)…",
        ["Analysis.DownloadingProgress"] = "Downloading the model… {0}",
        ["Analysis.Listening"] = "Listening to the beat…",
        ["Analysis.Cancelled"] = "Cancelled",
        ["Analysis.Failed"] = "Didn't work out: {0}",
        ["Analysis.TooShort"] = "the beat is shorter than three seconds — nothing to analyze",

        // Парсер
        ["Parser.Title"] = "PARSER",
        ["Parser.Platforms"] = "PLATFORMS",
        ["Parser.WhatToSearch"] = "WHAT TO SEARCH",
        ["Parser.Genre"] = "Genre / tag",
        ["Parser.GenreHint"] = "Searched as a track tag: rage, plugg, jerk, phonk. Empty — take what's popular",
        ["Parser.Filtering"] = "FILTERING",
        ["Parser.Plays"] = "Plays",
        ["Parser.PlaysHint"] = "Bandcamp doesn't expose play counts — the filter is skipped for it",
        ["Parser.From"] = "from",
        ["Parser.To"] = "to",
        ["Parser.Freshness"] = "Release freshness",
        ["Parser.FreshnessHint"] = "Posted something within the last N days. Empty — don't check",
        ["Parser.Days"] = "days",
        ["Parser.Country"] = "Country / language",
        ["Parser.CountryHint"] = "Matched against the profile field. Many artists leave it empty",
        ["Parser.CountryPlaceholder"] = "e.g. Russia",
        ["Parser.HowMany"] = "HOW MANY TO TAKE",
        ["Parser.MaxArtists"] = "Artists per platform",
        ["Parser.MaxArtistsHint"] = "A limit for each one separately: 12 means up to 48 in total from four",
        ["Parser.TracksPerArtist"] = "Tracks per artist",
        ["Parser.TracksHint"] = "The more, the longer the run — each artist costs a separate request",
        ["Parser.Search"] = "FIND",
        ["Parser.Back"] = "‹ BACK",
        ["Parser.SelectAll"] = "ALL",
        ["Parser.SelectNone"] = "NONE",
        ["Parser.Cancel"] = "CANCEL",
        ["Parser.Nickname"] = "NICKNAME",
        ["Parser.PlaysColumn"] = "PLAYS",
        ["Parser.Where"] = "WHERE",
        ["Parser.Tracks"] = "TRACKS",
        ["Parser.EmptyResult"] = "Nobody found. Loosen the filtering — for example, drop the plays range or freshness",
        ["Parser.PickSource"] = "Pick at least one platform",
        ["Parser.Starting"] = "Starting…",
        ["Parser.Cancelled"] = "Cancelled",
        ["Parser.Failed"] = "Didn't work out",
        ["Parser.Saving"] = "Saving {0}…",
        ["Parser.SaveFailed"] = "Couldn't save",
        ["Parser.Found"] = "Found {0}",
        ["Parser.NothingSelected"] = "NOTHING SELECTED",
        ["Parser.ImportButton"] = "ADD {0} TO DATABASE",
        ["Parser.Saved"] = "SAVED",
        ["Parser.AlreadyInDb"] = "ALREADY IN DATABASE",
        ["Parser.NoTracks"] = "no tracks",
        ["Parser.TracksCount"] = "{0} tracks",

        // Настройки
        ["Settings.Title"] = "SETTINGS",
        ["Settings.Reminders"] = "CRM REMINDERS",
        ["Settings.RemindAfter"] = "Remind after (days)",
        ["Settings.RemindAfterHint"] = "How many days before reminding about a beat that was assigned but never sent",
        ["Settings.DaysShort"] = "{0} d.",
        ["Settings.Parser"] = "PARSER",
        ["Settings.MediaFolder"] = "Media folder",
        ["Settings.Choose"] = "CHOOSE",
        ["Settings.ApiKeys"] = "PARSER API KEYS",
        ["Settings.LastFmKey"] = "Last.fm API key",
        ["Settings.LastFmHint"] = "Free at last.fm/api/account/create — needed for the Last.fm source",
        ["Settings.JamendoKey"] = "Jamendo client_id",
        ["Settings.JamendoHint"] = "Free at devportal.jamendo.com — needed for the Jamendo source",
        ["Settings.GeniusKey"] = "Genius access token",
        ["Settings.GeniusHint"] = "Free at genius.com/api-clients — socials and artist language",
        ["Settings.Language"] = "LANGUAGE",
        ["Settings.InterfaceLanguage"] = "Interface language",
        ["Settings.InterfaceLanguageHint"] = "Applies immediately, no restart needed",
        ["Settings.About"] = "ABOUT",
        ["Settings.AboutText"] = "Beat library, a roster of underground artists from five platforms, and artist matching by the sound of a beat.",
        ["Settings.BuiltWith"] = "Built with Avalonia 12 + .NET 9",
        ["Settings.Logs"] = "LOGS & DEBUG",
        ["Settings.EnableParserLogs"] = "Enable parser logs",
        ["Settings.EnableDevTools"] = "Enable Avalonia DevTools (F12)",
        ["Settings.VerboseHttp"] = "Verbose HTTP logging",
        ["Settings.LogFile"] = "Log file",
        ["Settings.OpenFolder"] = "OPEN FOLDER",

        // CRM и напоминания
        ["Crm.Title"] = "CRM",
        ["Crm.Empty"] = "Set a CRM status on an artist in the ARTISTS tab — they will show up here",
        ["Crm.MarkSent"] = "MARK SENT",
        ["Crm.Sent"] = "✓ sent",
        ["Crm.Pending"] = "⏳ pending",
        ["Reminder.Title"] = "TIME TO SEND",
        ["Reminder.Subtitle"] = "These beats are assigned but never sent",
        ["Reminder.OpenCrm"] = "OPEN CRM",
        ["Reminder.Later"] = "LATER",
    };

    public static readonly Dictionary<string, string> Russian = new()
    {
        // Главное окно
        ["Tabs.Beats"] = "БИТЫ",
        ["Tabs.Artists"] = "АРТИСТЫ",
        ["Status.Artists"] = "Артистов:",
        ["Status.Beats"] = "Битов:",
        ["Status.Parser"] = "ПАРСЕР: {0}",
        ["Parser.Idle"] = "Ожидание",

        // Кнопки на панелях
        ["Buttons.AddBeat"] = "+ ДОБАВИТЬ БИТ",
        ["Buttons.ImportFolder"] = "ИМПОРТ ПАПКИ",
        ["Buttons.AddArtist"] = "+ ДОБАВИТЬ АРТИСТА",
        ["Buttons.Parser"] = "⌕ ПАРСЕР",
        ["Buttons.Crm"] = "CRM",
        ["Buttons.Settings"] = "НАСТРОЙКИ",
        ["Buttons.Save"] = "СОХРАНИТЬ",
        ["Buttons.Cancel"] = "ОТМЕНА",
        ["Buttons.Delete"] = "УДАЛИТЬ",
        ["Buttons.Close"] = "ЗАКРЫТЬ",

        // Таблица битов
        ["Beats.Name"] = "НАЗВАНИЕ",
        ["Beats.Genre"] = "ТИП / ЖАНР",
        ["Beats.Bpm"] = "BPM",
        ["Beats.Key"] = "ТОНАЛЬНОСТЬ",
        ["Beats.Added"] = "ДОБАВЛЕН",
        ["Beats.Status"] = "СТАТУС",
        ["Beats.Empty"] = "ПРИМЕР — здесь появятся твои биты. Нажми + ДОБАВИТЬ БИТ",

        // Таблица артистов
        ["Artists.Nickname"] = "НИКНЕЙМ",
        ["Artists.Genre"] = "ТИП / ЖАНР",
        ["Artists.Plays"] = "ПРОСЛУШИВАНИЯ\n(всего)",
        ["Artists.Links"] = "Ссылки на соцсети и площадки",
        ["Artists.Language"] = "ЯЗЫК",
        ["Artists.Empty"] = "ПРИМЕР — здесь появятся артисты. Нажми + ДОБАВИТЬ АРТИСТА",

        // Фильтры
        ["Filter.Type"] = "ТИП",
        ["Filter.Key"] = "ТОНАЛЬНОСТЬ",
        ["Filter.Period"] = "ПЕРИОД",
        ["Filter.Plays"] = "ПРОСЛУШИВАНИЯ",
        ["Filter.Language"] = "ЯЗЫК",
        ["Filter.Search"] = "ПОИСК (КЛЮЧЕВОЕ СЛОВО)",
        ["Filter.Min"] = "от",
        ["Filter.Max"] = "до",

        // Карточка бита
        ["BeatEditor.Add"] = "ДОБАВИТЬ БИТ",
        ["BeatEditor.Edit"] = "РЕДАКТИРОВАТЬ БИТ",
        ["BeatEditor.License"] = "ЛИЦЕНЗИЯ (ЕСЛИ ПРОДАН)",
        ["BeatEditor.AssignArtists"] = "ПРИВЯЗАТЬ К АРТИСТАМ",
        ["BeatEditor.Similar"] = "ПОХОЖИЕ АРТИСТЫ",
        ["BeatEditor.Analyze"] = "АНАЛИЗ",
        ["BeatEditor.Stop"] = "СТОП",
        ["BeatEditor.SimilarHint"] = "Нажми АНАЛИЗ — подберём артистов, на чьё звучание похож бит",

        // Карточка артиста
        ["ArtistEditor.Add"] = "ДОБАВИТЬ АРТИСТА",
        ["ArtistEditor.Edit"] = "РЕДАКТИРОВАТЬ АРТИСТА",
        ["ArtistEditor.ScLink"] = "ССЫЛКА SOUNDCLOUD",
        ["ArtistEditor.Instagram"] = "INSTAGRAM",
        ["ArtistEditor.Spotify"] = "SPOTIFY",
        ["ArtistEditor.CrmStatus"] = "СТАТУС CRM",
        ["ArtistEditor.Notes"] = "ЗАМЕТКИ",
        ["ArtistEditor.AssignedBeats"] = "ПРИВЯЗАННЫЕ БИТЫ",
        ["ArtistEditor.NoneHint"] = "(можно пусто)",
        ["ArtistEditor.LanguageHint"] = "ENG / RU / ...",
        ["ArtistEditor.MatchingBeats"] = "ПОДХОДЯЩИЕ БИТЫ",
        ["ArtistEditor.NoMatches"] = "Пока ни один бит не совпал с этим артистом. Прогони свои биты через АНАЛИЗ в их карточках — подходящие появятся здесь.",
        ["ArtistEditor.UnknownArtist"] = "Модель не знает этого артиста: она обучена на 32 конкретных, и сопоставление идёт по имени. Для остальных блок остаётся пустым.",
        ["ArtistEditor.NoModel"] = "Нет файла с базой артистов — подбор недоступен.",

        // Анализ похожести
        ["Analysis.NoFile"] = "Файл бита не найден — анализировать нечего",
        ["Analysis.NoIndex"] = "Нет файла с базой артистов (artist_index.bin)",
        ["Analysis.Downloading"] = "Качаю модель (208 МБ, один раз)…",
        ["Analysis.DownloadingProgress"] = "Качаю модель… {0}",
        ["Analysis.Listening"] = "Слушаю бит…",
        ["Analysis.Cancelled"] = "Отменено",
        ["Analysis.Failed"] = "Не получилось: {0}",
        ["Analysis.TooShort"] = "бит короче трёх секунд — анализировать нечего",

        // Парсер
        ["Parser.Title"] = "ПАРСЕР",
        ["Parser.Platforms"] = "ПЛОЩАДКИ",
        ["Parser.WhatToSearch"] = "ЧТО ИСКАТЬ",
        ["Parser.Genre"] = "Жанр / тег",
        ["Parser.GenreHint"] = "Ищется как тег трека: rage, plugg, jerk, phonk. Пусто — берём популярное",
        ["Parser.Filtering"] = "ОТСЕВ",
        ["Parser.Plays"] = "Прослушивания",
        ["Parser.PlaysHint"] = "Bandcamp прослушивания не отдаёт — для него фильтр не применяется",
        ["Parser.From"] = "от",
        ["Parser.To"] = "до",
        ["Parser.Freshness"] = "Свежесть релизов",
        ["Parser.FreshnessHint"] = "Выкладывал что-то за последние N дней. Пусто — не проверяем",
        ["Parser.Days"] = "дней",
        ["Parser.Country"] = "Страна / язык",
        ["Parser.CountryHint"] = "Сверяется с полем в профиле. Многие артисты его не заполняют",
        ["Parser.CountryPlaceholder"] = "напр. Russia",
        ["Parser.HowMany"] = "СКОЛЬКО БРАТЬ",
        ["Parser.MaxArtists"] = "Артистов с каждой площадки",
        ["Parser.MaxArtistsHint"] = "Лимит на каждую отдельно: 12 — это до 48 суммарно с четырёх",
        ["Parser.TracksPerArtist"] = "Треков на артиста",
        ["Parser.TracksHint"] = "Чем больше, тем дольше прогон — на каждого уходит отдельный запрос",
        ["Parser.Search"] = "НАЙТИ",
        ["Parser.Back"] = "‹ НАЗАД",
        ["Parser.SelectAll"] = "ВСЕ",
        ["Parser.SelectNone"] = "НИКОГО",
        ["Parser.Cancel"] = "ОТМЕНА",
        ["Parser.Nickname"] = "НИКНЕЙМ",
        ["Parser.PlaysColumn"] = "ПЛЕИ",
        ["Parser.Where"] = "ГДЕ",
        ["Parser.Tracks"] = "ТРЕКИ",
        ["Parser.EmptyResult"] = "Никого не нашлось. Ослабь отсев — например, убери диапазон прослушиваний или свежесть",
        ["Parser.PickSource"] = "Выбери хотя бы одну площадку",
        ["Parser.Starting"] = "Запускаю…",
        ["Parser.Cancelled"] = "Отменено",
        ["Parser.Failed"] = "Не получилось",
        ["Parser.Saving"] = "Сохраняю {0}…",
        ["Parser.SaveFailed"] = "Сохранить не вышло",
        ["Parser.Found"] = "Найдено {0}",
        ["Parser.NothingSelected"] = "НИЧЕГО НЕ ВЫБРАНО",
        ["Parser.ImportButton"] = "ДОБАВИТЬ {0} В БАЗУ",
        ["Parser.Saved"] = "СОХРАНЁН",
        ["Parser.AlreadyInDb"] = "УЖЕ В БАЗЕ",
        ["Parser.NoTracks"] = "нет треков",
        ["Parser.TracksCount"] = "{0} треков",

        // Настройки
        ["Settings.Title"] = "НАСТРОЙКИ",
        ["Settings.Reminders"] = "НАПОМИНАНИЯ CRM",
        ["Settings.RemindAfter"] = "Напоминать через (дней)",
        ["Settings.RemindAfterHint"] = "Через сколько дней напоминать о привязанном, но не отправленном бите",
        ["Settings.DaysShort"] = "{0} дн.",
        ["Settings.Parser"] = "ПАРСЕР",
        ["Settings.MediaFolder"] = "Папка для медиа",
        ["Settings.Choose"] = "ВЫБРАТЬ",
        ["Settings.ApiKeys"] = "КЛЮЧИ ДЛЯ ПАРСЕРА",
        ["Settings.LastFmKey"] = "Ключ Last.fm",
        ["Settings.LastFmHint"] = "Бесплатно на last.fm/api/account/create — нужен для площадки Last.fm",
        ["Settings.JamendoKey"] = "Jamendo client_id",
        ["Settings.JamendoHint"] = "Бесплатно на devportal.jamendo.com — нужен для площадки Jamendo",
        ["Settings.GeniusKey"] = "Токен Genius",
        ["Settings.GeniusHint"] = "Бесплатно на genius.com/api-clients — соцсети и язык артиста",
        ["Settings.Language"] = "ЯЗЫК",
        ["Settings.InterfaceLanguage"] = "Язык интерфейса",
        ["Settings.InterfaceLanguageHint"] = "Применяется сразу, перезапуск не нужен",
        ["Settings.About"] = "О ПРОГРАММЕ",
        ["Settings.AboutText"] = "Библиотека битов, база андеграунд-артистов с пяти площадок и подбор артистов под звучание бита.",
        ["Settings.BuiltWith"] = "Собрано на Avalonia 12 + .NET 9",
        ["Settings.Logs"] = "ЛОГИ И ОТЛАДКА",
        ["Settings.EnableParserLogs"] = "Писать логи парсера",
        ["Settings.EnableDevTools"] = "Включить Avalonia DevTools (F12)",
        ["Settings.VerboseHttp"] = "Подробный лог HTTP",
        ["Settings.LogFile"] = "Файл лога",
        ["Settings.OpenFolder"] = "ОТКРЫТЬ ПАПКУ",

        // CRM и напоминания
        ["Crm.Title"] = "CRM",
        ["Crm.Empty"] = "Пометь артистам CRM-статус на вкладке АРТИСТЫ — они появятся здесь",
        ["Crm.MarkSent"] = "ОТМЕТИТЬ ОТПРАВЛЕННЫМ",
        ["Crm.Sent"] = "✓ отправлен",
        ["Crm.Pending"] = "⏳ ждёт отправки",
        ["Reminder.Title"] = "ПОРА ОТПРАВИТЬ",
        ["Reminder.Subtitle"] = "Эти биты привязаны, но ещё не отправлены",
        ["Reminder.OpenCrm"] = "ОТКРЫТЬ CRM",
        ["Reminder.Later"] = "ПОЗЖЕ",
    };
}
