using System.Collections.Generic;

namespace MessedUpSearchA.Services.Localization;

/// <summary>
/// Сами строки. Английский — база: если ключа нет в русском, покажется английский,
/// а не пустота. Ключи именуются «экран.элемент», чтобы искать было по чему.
///
/// Сюда не попадают данные: названия жанров, статусы битов (POTENTIAL/FREE/SOLD),
/// CRM-статусы и содержимое фейкового превью. Это значения, а не подписи — они
/// хранятся в базе и от языка интерфейса не зависят.
/// </summary>
public static class LocalizationStrings
{
    public static readonly Dictionary<string, string> English = new()
    {
        // Главное окно
        ["Tabs.Beats"] = "BEATS BASE",
        ["Tabs.Artists"] = "ARTISTS",
        ["Status.Artists"] = "Artists:",
        ["Status.Beats"] = "Beats:",
        ["Status.Parser"] = "PARSER: {0}",
        ["Player.Loading"] = "Loading…",
        ["Player.NoFile"] = "File not found — it was moved or deleted",
        ["Player.NoAudio"] = "no audio available for this track",
        ["Player.Failed"] = "Can't play: {0}",
        ["ArtistEditor.Tracks"] = "TRACKS",
        ["ArtistEditor.NoAssignedBeats"] = "No beats assigned yet — tick this artist in a beat card.",
        ["ArtistEditor.NoTracks"] = "No tracks yet — they appear after the parser imports the artist.",
        ["Parser.Idle"] = "Idle",
        ["Parser.Running"] = "searching",

        // Кнопки на панелях
        ["Buttons.AddBeat"] = "+ ADD BEAT",
        ["Buttons.ImportFolder"] = "IMPORT FOLDER",
        ["Buttons.AddArtist"] = "+ ADD ARTIST",
        ["Buttons.Parser"] = "⌕ PARSER",
        ["Buttons.Crm"] = "CRM",
        ["Buttons.Settings"] = "SETTINGS",
        ["Buttons.Save"] = "SAVE",
        ["Buttons.Cancel"] = "CANCEL",
        ["Buttons.Delete"] = "DELETE",
        ["Buttons.Close"] = "CLOSE",

        // Таблица битов
        ["Beats.Name"] = "BEAT NAME",
        ["Beats.Genre"] = "TYPE / GENRE",
        ["Beats.Bpm"] = "BPM",
        ["Beats.Key"] = "KEY",
        ["Beats.Added"] = "ADDED",
        ["Beats.Status"] = "STATUS",
        ["Beats.Empty"] = "EXAMPLE — your beats will appear here. Press + ADD BEAT",

        // Таблица артистов
        ["Artists.Nickname"] = "NICKNAME",
        ["Artists.Genre"] = "TYPE / GENRE",
        ["Artists.Plays"] = "PLAYS\n(total)",
        ["Artists.Links"] = "LINKS",
        ["Artists.Language"] = "LANGUAGE",
        ["Artists.Empty"] = "EXAMPLE — your artists will appear here. Press + ADD ARTIST",

        // Фильтры
        ["Filter.Type"] = "TYPE",
        ["Filter.Key"] = "KEY",
        ["Filter.Period"] = "PERIOD",
        ["Filter.Plays"] = "PLAYS",
        ["Filter.Language"] = "LANGUAGE",
        ["Filter.Search"] = "SEARCH (KEY WORD)",
        ["Filter.OnlyWithEmail"] = "Only artists with email",
        ["Filter.Min"] = "min",
        ["Filter.Max"] = "max",

        // Карточка бита
        ["BeatEditor.Add"] = "ADD BEAT",
        ["BeatEditor.Edit"] = "EDIT BEAT",
        ["BeatEditor.License"] = "LICENSE (IF SOLD)",
        ["BeatEditor.ShareUrl"] = "LINK TO THE BEAT",
        ["BeatEditor.AssignArtists"] = "ASSIGN TO ARTISTS",
        ["BeatEditor.Similar"] = "SIMILAR ARTISTS",
        ["BeatEditor.Analyze"] = "ANALYZE",
        ["BeatEditor.Stop"] = "STOP",
        ["BeatEditor.SimilarHint"] = "Press ANALYZE — we'll find artists whose sound your beat resembles",

        // Карточка артиста
        ["ArtistEditor.Add"] = "ADD ARTIST",
        ["ArtistEditor.Edit"] = "EDIT ARTIST",
        ["ArtistEditor.ProfileLink"] = "PROFILE LINK",
        ["ArtistEditor.PlatformLink"] = "{0} LINK",
        ["ArtistEditor.Instagram"] = "INSTAGRAM",
        ["ArtistEditor.Spotify"] = "SPOTIFY",
        ["ArtistEditor.CrmStatus"] = "CRM STATUS",
        ["ArtistEditor.Notes"] = "NOTES",
        ["ArtistEditor.Email"] = "EMAIL",
        ["ArtistEditor.OtherContact"] = "OTHER CONTACT",
        ["ArtistEditor.OtherContactHint"] = "manager, Discord, WhatsApp…",
        ["ArtistEditor.FindContacts"] = "FIND IN PROFILE",
        ["ArtistEditor.UseHint"] = "Put into the card — saved with SAVE",
        ["ArtistEditor.NoContactsFound"] = "No contacts in the profile description",
        ["ArtistEditor.ContactsFailed"] = "Could not load the profile — check the connection",
        ["ArtistEditor.AssignedBeats"] = "ASSIGNED BEATS",
        ["ArtistEditor.NoneHint"] = "(can be empty)",
        ["ArtistEditor.LanguageHint"] = "ENG / RU / ...",
        ["ArtistEditor.MatchingBeats"] = "BEATS THAT FIT",
        ["ArtistEditor.NoMatches"] = "No beat matched this artist yet. Analyze your beats on their cards — matching ones will show up here.",
        ["ArtistEditor.UnknownArtist"] = "This artist isn't in the index yet, so sound matching doesn't consider them. Matching beats will show up once they're indexed.",
        ["ArtistEditor.NoModel"] = "Artist database file is missing — matching is unavailable.",

        // Анализ похожести (сообщения из кода)
        ["Analysis.NoFile"] = "Beat file not found — nothing to analyze",
        ["Analysis.NoIndex"] = "Sound-matching model files are missing (Assets/Models) — reinstall the app",
        ["Analysis.Listening"] = "Listening to the beat…",
        ["Analysis.DownloadingIndex"] = "Downloading the artist index (one time)…",
        ["Analysis.ImportFailed"] = "Couldn't add {0}: {1}",
        ["BeatEditor.SoundsLike"] = "sounds like: {0}",
        ["BeatEditor.PlayTrack"] = "Listen to their track",
        ["BeatEditor.PlayNearest"] = "Closest to the beat: «{0}»",
        ["BeatEditor.AddToBase"] = "Add to my artists",
        ["BeatEditor.OpenProfile"] = "Open profile",
        ["Analysis.Cancelled"] = "Cancelled",
        ["Analysis.Failed"] = "Didn't work out: {0}",
        ["Analysis.TooShort"] = "the beat is shorter than three seconds — nothing to analyze",

        // Парсер
        ["Parser.Title"] = "PARSER",
        ["Parser.Platforms"] = "PLATFORMS",
        ["Parser.WhatToSearch"] = "WHAT TO SEARCH",
        ["Parser.Genre"] = "Genre / tag",
        ["Parser.GenreHint"] = "Searched as a track tag: rage, plugg, jerk, phonk. Empty — take what's popular",
        ["Parser.Filtering"] = "FILTERING",
        ["Parser.Plays"] = "Plays",
        ["Parser.PlaysHint"] = "Bandcamp doesn't expose play counts — the filter is skipped for it",
        ["Parser.From"] = "from",
        ["Parser.To"] = "to",
        ["Parser.Freshness"] = "Release freshness",
        ["Parser.FreshnessHint"] = "Posted something within the last N days. Empty — don't check",
        ["Parser.Days"] = "days",
        ["Parser.Country"] = "Country / language",
        ["Parser.CountryHint"] = "Matched against the profile field. Many artists leave it empty",
        ["Parser.CountryPlaceholder"] = "e.g. Russia",
        ["Parser.HowMany"] = "HOW MANY TO TAKE",
        ["Parser.MaxArtists"] = "Artists per platform",
        ["Parser.MaxArtistsHint"] = "A limit for each platform separately: 12 means up to 60 in total from five",
        ["Crm.SentCount"] = "{0}/{1} sent",
        ["Value.Common"] = "Unknown",
        ["Parser.TracksPerArtist"] = "Tracks per artist",
        ["Parser.TracksHint"] = "The more, the longer the run — each artist costs a separate request",
        ["Parser.Search"] = "FIND",
        ["Parser.Back"] = "‹ BACK",
        ["Parser.SelectAll"] = "ALL",
        ["Parser.SelectNone"] = "NONE",
        ["Parser.Cancel"] = "CANCEL",
        ["Parser.Nickname"] = "NICKNAME",
        ["Parser.PlaysColumn"] = "PLAYS",
        ["Parser.Where"] = "WHERE",
        ["Parser.Tracks"] = "TRACKS",
        ["Parser.EmptyResult"] = "Nobody found. Loosen the filtering — for example, drop the plays range or freshness",
        ["Parser.PickSource"] = "Pick at least one platform",
        ["Parser.Starting"] = "Starting…",
        ["Parser.Cancelled"] = "Cancelled",
        ["Parser.Failed"] = "Didn't work out",
        ["Parser.Saving"] = "Saving {0}…",
        ["Parser.SaveFailed"] = "Couldn't save",
        ["Parser.Found"] = "Found {0}",
        ["Parser.NothingSelected"] = "NOTHING SELECTED",
        ["Parser.ImportButton"] = "ADD {0} TO DATABASE",
        ["Parser.Saved"] = "SAVED",
        ["Parser.AlreadyInDb"] = "ALREADY IN DATABASE",
        ["Parser.NoTracks"] = "no tracks",
        ["Parser.TracksCount"] = "{0} tracks",

        // Настройки
        ["Settings.Title"] = "SETTINGS",
        ["Settings.Reminders"] = "CRM REMINDERS",
        ["Settings.RemindAfter"] = "Remind after (days)",
        ["Settings.RemindAfterHint"] = "How many days before reminding about a beat that was assigned but never sent",
        ["Settings.DaysShort"] = "{0} d.",
        ["Settings.Parser"] = "PARSER",
        ["Settings.MediaFolder"] = "Media folder",
        ["Settings.Choose"] = "CHOOSE",
        ["Settings.ApiKeys"] = "PARSER API KEYS",
        ["Settings.LastFmKey"] = "Last.fm API key",
        ["Settings.LastFmHint"] = "Free at last.fm/api/account/create — needed for the Last.fm source",
        ["Settings.JamendoKey"] = "Jamendo client_id",
        ["Settings.JamendoHint"] = "Free at devportal.jamendo.com — needed for the Jamendo source",
        ["Settings.GeniusKey"] = "Genius access token",
        ["Settings.GeniusHint"] = "Free at genius.com/api-clients — socials and artist language",
        ["Settings.Language"] = "LANGUAGE",
        ["Settings.InterfaceLanguage"] = "Interface language",
        ["Settings.InterfaceLanguageHint"] = "Applies immediately, no restart needed",
        ["Settings.About"] = "ABOUT",
        ["Settings.Mail"] = "EMAIL FOR PITCHES",
        ["Mail.Address"] = "Your email",
        ["Mail.AddressHint"] = "Pitches go out from your own mailbox — artists see you, not a service",
        ["Mail.SenderName"] = "Name in the letter",
        ["Mail.SenderNameHint"] = "Sender name and {my_name} in templates",
        ["Mail.Password"] = "App password",
        ["Mail.PasswordSaved"] = "saved in the system keychain",
        ["Mail.ForgetPassword"] = "FORGET",
        ["Mail.Servers"] = "Servers",
        ["Mail.ServersHint"] = "Filled in automatically for Gmail, Yandex, Mail.ru, iCloud, Rambler",
        ["Mail.DailyLimit"] = "Emails per day, max",
        ["Mail.DailyLimitHint"] = "Mail services block personal mailboxes that send too much at once",
        ["Mail.SaveAndTest"] = "SAVE AND TEST",
        ["Mail.HelpGmail"] = "Gmail: turn on 2-Step Verification, then create an app password at myaccount.google.com/apppasswords",
        ["Mail.HelpYandex"] = "Yandex: id.yandex.ru → Security → App passwords (type \"Mail\"); in Mail settings allow IMAP for email clients",
        ["Mail.HelpMailRu"] = "Mail.ru: account settings → Security → Passwords for external apps",
        ["Mail.HelpIcloud"] = "iCloud: account.apple.com → Sign-In and Security → App-Specific Passwords",
        ["Mail.HelpOther"] = "Use an app password if your mail service has them; otherwise your regular password",
        ["Mail.SetupFirst"] = "Set up your email in Settings first",
        ["Mail.KeychainFailed"] = "Could not save the password to the system keychain",
        ["Mail.NoPassword"] = "Enter the app password",
        ["Mail.Testing"] = "Sending a test email to yourself…",
        ["Mail.TestSubject"] = "MessedUpSearch: test email",
        ["Mail.TestBody"] = "If you see this, pitches will go out from this mailbox.",
        ["Mail.TestOk"] = "Done — check your inbox, the test email is there",
        ["Mail.AuthFailed"] = "The mail server rejected the password — you need an app password, not the account one",
        ["Mail.ConnectionFailed"] = "Could not reach the mail server — check the connection and server addresses",
        ["Mail.NotConfigured"] = "Email is not set up — see Settings",
        ["Mail.LimitReached"] = "Daily limit of {0} emails reached — the rest tomorrow",
        ["Mail.Sending"] = "EMAIL: {0}/{1}",
        ["Mail.Waiting"] = "EMAIL: {0}/{1} · NEXT IN {2} S",
        ["Mail.Stopped"] = "Pitching stopped",
        ["Mail.Done"] = "Sent {0} of {1}",
        ["Mail.NoEmail"] = "no email",
        ["Mail.AlreadySent"] = "this beat was already sent on {0}",
        ["Mail.RecentlyWritten"] = "you wrote {0} d. ago",
        ["Mail.RedFlag"] = "red flag",
        ["Mail.NoLink"] = "The beat has no link — add it in the beat card (\"Link to the beat\")",
        ["Mail.EmptyBody"] = "The email is empty",
        ["Mail.OverLimit"] = "Only {0} more emails can go out today",
        ["Mail.Summary"] = "Selected: {0} · left today: {1}",
        ["Mail.NewTemplateName"] = "My template {0}",
        ["Mail.Started"] = "Pitching started: {0} email(s), one every 20–40 s",
        ["Mail.Title"] = "PITCH",
        ["Mail.Recipients"] = "RECIPIENTS",
        ["Mail.UseHintTip"] = "Found in the profile — save to the card and send",
        ["Mail.NewTemplate"] = "+ TEMPLATE",
        ["Mail.DeleteTemplate"] = "DELETE",
        ["Mail.Subject"] = "Subject",
        ["Mail.Preview"] = "PREVIEW FOR",
        ["Mail.Send"] = "SEND",
        ["Mail.Stop"] = "STOP",
        ["Mail.SendBeat"] = "PITCH",
        ["Mail.SendPicked"] = "PITCH TO SELECTED",
        ["Settings.ReportProblem"] = "REPORT A PROBLEM",
        ["Settings.ReportIntro"] = "What happened and what did you do right before it?",
        ["Settings.Interface"] = "INTERFACE",
        ["Settings.Animations"] = "Animations",
        ["Settings.AnimationsHint"] = "Windows appear and fade smoothly, analysis results slide in one by one",
        ["Settings.AnimationsSystem"] = "Reduce Motion is on in your system — animations are simplified to fades",
        ["Toast.Sent"] = "Sent ✓",
        ["Toast.Added"] = "{0} added to your artists",
        ["Toast.AddedMany"] = "Artists added: {0}",
        ["Settings.Sounds"] = "Sounds",
        ["Settings.SoundsHint"] = "Quiet sounds on four events: analysis done, beat sent, ★, parser finished",
        ["Settings.Logs"] = "LOGS & DEBUG",
        ["Settings.EnableParserLogs"] = "Enable parser logs",
        ["Settings.EnableDevTools"] = "Enable Avalonia DevTools (F12)",
        ["Settings.VerboseHttp"] = "Verbose HTTP logging",
        ["Settings.LogFile"] = "Log file",
        ["Settings.OpenFolder"] = "OPEN FOLDER",

        // CRM и напоминания
        ["Crm.Title"] = "CRM",
        ["Crm.Empty"] = "Set a CRM status on an artist in the ARTISTS tab — they will show up here",
        ["Crm.MarkSent"] = "MARK SENT",
        ["Crm.Sent"] = "✓ sent",
        ["Crm.Pending"] = "⏳ pending",
        ["Reminder.Title"] = "TIME TO SEND",
        ["Reminder.Subtitle"] = "These beats are assigned but never sent",
        ["Reminder.OpenCrm"] = "OPEN CRM",
        ["Reminder.Later"] = "LATER",
    };

    public static readonly Dictionary<string, string> Russian = new()
    {
        // Главное окно
        ["Tabs.Beats"] = "БИТЫ",
        ["Tabs.Artists"] = "АРТИСТЫ",
        ["Status.Artists"] = "Артистов:",
        ["Status.Beats"] = "Битов:",
        ["Status.Parser"] = "ПАРСЕР: {0}",
        ["Player.Loading"] = "Загрузка…",
        ["Player.NoFile"] = "Файл не найден — его перенесли или удалили",
        ["Player.NoAudio"] = "у этого трека нет звука",
        ["Player.Failed"] = "Не играет: {0}",
        ["ArtistEditor.Tracks"] = "ТРЕКИ",
        ["ArtistEditor.NoAssignedBeats"] = "Пока ни одного бита — отметь артиста в карточке бита.",
        ["ArtistEditor.NoTracks"] = "Треков пока нет — они появятся после импорта артиста парсером.",
        ["Parser.Idle"] = "Ожидание",
        ["Parser.Running"] = "идёт поиск",

        // Кнопки на панелях
        ["Buttons.AddBeat"] = "+ ДОБАВИТЬ БИТ",
        ["Buttons.ImportFolder"] = "ИМПОРТ ПАПКИ",
        ["Buttons.AddArtist"] = "+ ДОБАВИТЬ АРТИСТА",
        ["Buttons.Parser"] = "⌕ ПАРСЕР",
        ["Buttons.Crm"] = "CRM",
        ["Buttons.Settings"] = "НАСТРОЙКИ",
        ["Buttons.Save"] = "СОХРАНИТЬ",
        ["Buttons.Cancel"] = "ОТМЕНА",
        ["Buttons.Delete"] = "УДАЛИТЬ",
        ["Buttons.Close"] = "ЗАКРЫТЬ",

        // Таблица битов
        ["Beats.Name"] = "НАЗВАНИЕ",
        ["Beats.Genre"] = "ТИП / ЖАНР",
        ["Beats.Bpm"] = "BPM",
        ["Beats.Key"] = "ТОНАЛЬНОСТЬ",
        ["Beats.Added"] = "ДОБАВЛЕН",
        ["Beats.Status"] = "СТАТУС",
        ["Beats.Empty"] = "ПРИМЕР — здесь появятся твои биты. Нажми + ДОБАВИТЬ БИТ",

        // Таблица артистов
        ["Artists.Nickname"] = "НИКНЕЙМ",
        ["Artists.Genre"] = "ТИП / ЖАНР",
        ["Artists.Plays"] = "ПРОСЛУШИВАНИЯ\n(всего)",
        ["Artists.Links"] = "ССЫЛКИ",
        ["Artists.Language"] = "ЯЗЫК",
        ["Artists.Empty"] = "ПРИМЕР — здесь появятся артисты. Нажми + ДОБАВИТЬ АРТИСТА",

        // Фильтры
        ["Filter.Type"] = "ТИП",
        ["Filter.Key"] = "ТОНАЛЬНОСТЬ",
        ["Filter.Period"] = "ПЕРИОД",
        ["Filter.Plays"] = "ПРОСЛУШИВАНИЯ",
        ["Filter.Language"] = "ЯЗЫК",
        ["Filter.Search"] = "ПОИСК (КЛЮЧЕВОЕ СЛОВО)",
        ["Filter.OnlyWithEmail"] = "Только с почтой",
        ["Filter.Min"] = "от",
        ["Filter.Max"] = "до",

        // Карточка бита
        ["BeatEditor.Add"] = "ДОБАВИТЬ БИТ",
        ["BeatEditor.Edit"] = "РЕДАКТИРОВАТЬ БИТ",
        ["BeatEditor.License"] = "ЛИЦЕНЗИЯ (ЕСЛИ ПРОДАН)",
        ["BeatEditor.ShareUrl"] = "ССЫЛКА НА БИТ",
        ["BeatEditor.AssignArtists"] = "ПРИВЯЗАТЬ К АРТИСТАМ",
        ["BeatEditor.Similar"] = "ПОХОЖИЕ АРТИСТЫ",
        ["BeatEditor.Analyze"] = "АНАЛИЗ",
        ["BeatEditor.Stop"] = "СТОП",
        ["BeatEditor.SimilarHint"] = "Нажми АНАЛИЗ — подберём артистов, на чьё звучание похож бит",

        // Карточка артиста
        ["ArtistEditor.Add"] = "ДОБАВИТЬ АРТИСТА",
        ["ArtistEditor.Edit"] = "РЕДАКТИРОВАТЬ АРТИСТА",
        ["ArtistEditor.ProfileLink"] = "ССЫЛКА НА ПРОФИЛЬ",
        ["ArtistEditor.PlatformLink"] = "ССЫЛКА {0}",
        ["ArtistEditor.Instagram"] = "INSTAGRAM",
        ["ArtistEditor.Spotify"] = "SPOTIFY",
        ["ArtistEditor.CrmStatus"] = "СТАТУС CRM",
        ["ArtistEditor.Notes"] = "ЗАМЕТКИ",
        ["ArtistEditor.Email"] = "ПОЧТА",
        ["ArtistEditor.OtherContact"] = "ДРУГОЙ КОНТАКТ",
        ["ArtistEditor.OtherContactHint"] = "менеджер, Discord, WhatsApp…",
        ["ArtistEditor.FindContacts"] = "НАЙТИ В ПРОФИЛЕ",
        ["ArtistEditor.UseHint"] = "В карточку — сохранится по SAVE",
        ["ArtistEditor.NoContactsFound"] = "В описании профиля контактов нет",
        ["ArtistEditor.ContactsFailed"] = "Не удалось открыть профиль — проверь интернет",
        ["ArtistEditor.AssignedBeats"] = "ПРИВЯЗАННЫЕ БИТЫ",
        ["ArtistEditor.NoneHint"] = "(можно пусто)",
        ["ArtistEditor.LanguageHint"] = "ENG / RU / ...",
        ["ArtistEditor.MatchingBeats"] = "ПОДХОДЯЩИЕ БИТЫ",
        ["ArtistEditor.NoMatches"] = "Пока ни один бит не совпал с этим артистом. Прогони свои биты через АНАЛИЗ в их карточках — подходящие появятся здесь.",
        ["ArtistEditor.UnknownArtist"] = "Этого артиста пока нет в индексе — подбор по звуку его не учитывает. Подходящие биты появятся, когда он туда попадёт.",
        ["ArtistEditor.NoModel"] = "Нет файла с базой артистов — подбор недоступен.",

        // Анализ похожести
        ["Analysis.NoFile"] = "Файл бита не найден — анализировать нечего",
        ["Analysis.NoIndex"] = "Нет файлов модели подбора (Assets/Models) — переустанови приложение",
        ["Analysis.Listening"] = "Слушаю бит…",
        ["Analysis.DownloadingIndex"] = "Качаю индекс артистов (один раз)…",
        ["Analysis.ImportFailed"] = "Не получилось добавить {0}: {1}",
        ["BeatEditor.SoundsLike"] = "звучит как: {0}",
        ["BeatEditor.PlayTrack"] = "Послушать его трек",
        ["BeatEditor.PlayNearest"] = "Ближе всего к биту: «{0}»",
        ["BeatEditor.AddToBase"] = "Добавить в мои артисты",
        ["BeatEditor.OpenProfile"] = "Открыть профиль",
        ["Analysis.Cancelled"] = "Отменено",
        ["Analysis.Failed"] = "Не получилось: {0}",
        ["Analysis.TooShort"] = "бит короче трёх секунд — анализировать нечего",

        // Парсер
        ["Parser.Title"] = "ПАРСЕР",
        ["Parser.Platforms"] = "ПЛОЩАДКИ",
        ["Parser.WhatToSearch"] = "ЧТО ИСКАТЬ",
        ["Parser.Genre"] = "Жанр / тег",
        ["Parser.GenreHint"] = "Ищется как тег трека: rage, plugg, jerk, phonk. Пусто — берём популярное",
        ["Parser.Filtering"] = "ОТСЕВ",
        ["Parser.Plays"] = "Прослушивания",
        ["Parser.PlaysHint"] = "Bandcamp прослушивания не отдаёт — для него фильтр не применяется",
        ["Parser.From"] = "от",
        ["Parser.To"] = "до",
        ["Parser.Freshness"] = "Свежесть релизов",
        ["Parser.FreshnessHint"] = "Выкладывал что-то за последние N дней. Пусто — не проверяем",
        ["Parser.Days"] = "дней",
        ["Parser.Country"] = "Страна / язык",
        ["Parser.CountryHint"] = "Сверяется с полем в профиле. Многие артисты его не заполняют",
        ["Parser.CountryPlaceholder"] = "напр. Russia",
        ["Parser.HowMany"] = "СКОЛЬКО БРАТЬ",
        ["Parser.MaxArtists"] = "Артистов с каждой площадки",
        ["Parser.MaxArtistsHint"] = "Лимит на каждую площадку отдельно: 12 — это до 60 суммарно с пяти",
        ["Crm.SentCount"] = "отправлено {0}/{1}",
        ["Value.ALL"] = "ВСЕ",
        ["Value.All time"] = "За всё время",
        ["Value.Today"] = "Сегодня",
        ["Value.This week"] = "Эта неделя",
        ["Value.This month"] = "Этот месяц",
        ["Value.This year"] = "Этот год",
        ["Value.Common"] = "Не определён",
        ["Value.English"] = "Английский",
        ["Value.Russian"] = "Русский",
        ["Value.Vietnamese"] = "Вьетнамский",
        ["Value.Spanish"] = "Испанский",
        ["Value.French"] = "Французский",
        ["Value.German"] = "Немецкий",
        ["Value.Portuguese"] = "Португальский",
        ["Value.Italian"] = "Итальянский",
        ["Value.Japanese"] = "Японский",
        ["Value.Korean"] = "Корейский",
        ["Value.Chinese"] = "Китайский",
        ["Value.Arabic"] = "Арабский",
        ["Parser.TracksPerArtist"] = "Треков на артиста",
        ["Parser.TracksHint"] = "Чем больше, тем дольше прогон — на каждого уходит отдельный запрос",
        ["Parser.Search"] = "НАЙТИ",
        ["Parser.Back"] = "‹ НАЗАД",
        ["Parser.SelectAll"] = "ВСЕ",
        ["Parser.SelectNone"] = "НИКОГО",
        ["Parser.Cancel"] = "ОТМЕНА",
        ["Parser.Nickname"] = "НИКНЕЙМ",
        ["Parser.PlaysColumn"] = "ПЛЕИ",
        ["Parser.Where"] = "ГДЕ",
        ["Parser.Tracks"] = "ТРЕКИ",
        ["Parser.EmptyResult"] = "Никого не нашлось. Ослабь отсев — например, убери диапазон прослушиваний или свежесть",
        ["Parser.PickSource"] = "Выбери хотя бы одну площадку",
        ["Parser.Starting"] = "Запускаю…",
        ["Parser.Cancelled"] = "Отменено",
        ["Parser.Failed"] = "Не получилось",
        ["Parser.Saving"] = "Сохраняю {0}…",
        ["Parser.SaveFailed"] = "Сохранить не вышло",
        ["Parser.Found"] = "Найдено {0}",
        ["Parser.NothingSelected"] = "НИЧЕГО НЕ ВЫБРАНО",
        ["Parser.ImportButton"] = "ДОБАВИТЬ {0} В БАЗУ",
        ["Parser.Saved"] = "СОХРАНЁН",
        ["Parser.AlreadyInDb"] = "УЖЕ В БАЗЕ",
        ["Parser.NoTracks"] = "нет треков",
        ["Parser.TracksCount"] = "{0} треков",

        // Настройки
        ["Settings.Title"] = "НАСТРОЙКИ",
        ["Settings.Reminders"] = "НАПОМИНАНИЯ CRM",
        ["Settings.RemindAfter"] = "Напоминать через (дней)",
        ["Settings.RemindAfterHint"] = "Через сколько дней напоминать о привязанном, но не отправленном бите",
        ["Settings.DaysShort"] = "{0} дн.",
        ["Settings.Parser"] = "ПАРСЕР",
        ["Settings.MediaFolder"] = "Папка для медиа",
        ["Settings.Choose"] = "ВЫБРАТЬ",
        ["Settings.ApiKeys"] = "КЛЮЧИ ДЛЯ ПАРСЕРА",
        ["Settings.LastFmKey"] = "Ключ Last.fm",
        ["Settings.LastFmHint"] = "Бесплатно на last.fm/api/account/create — нужен для площадки Last.fm",
        ["Settings.JamendoKey"] = "Jamendo client_id",
        ["Settings.JamendoHint"] = "Бесплатно на devportal.jamendo.com — нужен для площадки Jamendo",
        ["Settings.GeniusKey"] = "Токен Genius",
        ["Settings.GeniusHint"] = "Бесплатно на genius.com/api-clients — соцсети и язык артиста",
        ["Settings.Language"] = "ЯЗЫК",
        ["Settings.InterfaceLanguage"] = "Язык интерфейса",
        ["Settings.InterfaceLanguageHint"] = "Применяется сразу, перезапуск не нужен",
        ["Settings.About"] = "О ПРОГРАММЕ",
        ["Settings.Mail"] = "ПОЧТА ДЛЯ РАССЫЛКИ",
        ["Mail.Address"] = "Твоя почта",
        ["Mail.AddressHint"] = "Письма уходят с твоего ящика — артист видит тебя, а не сервис",
        ["Mail.SenderName"] = "Имя в письме",
        ["Mail.SenderNameHint"] = "Отправитель и {my_name} в шаблонах",
        ["Mail.Password"] = "Пароль приложения",
        ["Mail.PasswordSaved"] = "сохранён в связке ключей",
        ["Mail.ForgetPassword"] = "ЗАБЫТЬ",
        ["Mail.Servers"] = "Серверы",
        ["Mail.ServersHint"] = "Для Gmail, Яндекса, Mail.ru, iCloud и Рамблера подставляются сами",
        ["Mail.DailyLimit"] = "Писем в сутки, не больше",
        ["Mail.DailyLimitHint"] = "Почтовые сервисы блокируют личные ящики, которые шлют слишком много разом",
        ["Mail.SaveAndTest"] = "СОХРАНИТЬ И ПРОВЕРИТЬ",
        ["Mail.HelpGmail"] = "Gmail: включи двухэтапную проверку, потом создай пароль приложения на myaccount.google.com/apppasswords",
        ["Mail.HelpYandex"] = "Яндекс: id.yandex.ru → Безопасность → Пароли приложений (тип «Почта»); в настройках Почты разреши IMAP для почтовых программ",
        ["Mail.HelpMailRu"] = "Mail.ru: настройки аккаунта → Безопасность → Пароли для внешних приложений",
        ["Mail.HelpIcloud"] = "iCloud: account.apple.com → Вход и безопасность → Пароли для приложений",
        ["Mail.HelpOther"] = "Пароль приложения, если у твоей почты они есть; иначе обычный пароль",
        ["Mail.SetupFirst"] = "Сначала настрой почту в настройках",
        ["Mail.KeychainFailed"] = "Не удалось сохранить пароль в связку ключей",
        ["Mail.NoPassword"] = "Введи пароль приложения",
        ["Mail.Testing"] = "Отправляю тестовое письмо самому себе…",
        ["Mail.TestSubject"] = "MessedUpSearch: тестовое письмо",
        ["Mail.TestBody"] = "Если ты это видишь — рассылка будет уходить с этого ящика.",
        ["Mail.TestOk"] = "Готово — проверь входящие, тестовое письмо там",
        ["Mail.AuthFailed"] = "Почта не приняла пароль — нужен пароль приложения, а не от аккаунта",
        ["Mail.ConnectionFailed"] = "Не удалось подключиться к почтовому серверу — проверь интернет и адреса серверов",
        ["Mail.NotConfigured"] = "Почта не настроена — загляни в настройки",
        ["Mail.LimitReached"] = "Лимит {0} писем на сегодня — остальные завтра",
        ["Mail.Sending"] = "ПОЧТА: {0}/{1}",
        ["Mail.Waiting"] = "ПОЧТА: {0}/{1} · СЛЕДУЮЩЕЕ ЧЕРЕЗ {2} С",
        ["Mail.Stopped"] = "Рассылка остановлена",
        ["Mail.Done"] = "Отправлено {0} из {1}",
        ["Mail.NoEmail"] = "нет почты",
        ["Mail.AlreadySent"] = "этот бит уже отправлял {0}",
        ["Mail.RecentlyWritten"] = "писал {0} дн. назад",
        ["Mail.RedFlag"] = "ред-флаг",
        ["Mail.NoLink"] = "У бита нет ссылки — добавь её в карточке бита («Ссылка на бит»)",
        ["Mail.EmptyBody"] = "Письмо пустое",
        ["Mail.OverLimit"] = "Сегодня можно отправить ещё {0}",
        ["Mail.Summary"] = "Выбрано: {0} · осталось на сегодня: {1}",
        ["Mail.NewTemplateName"] = "Мой шаблон {0}",
        ["Mail.Started"] = "Рассылка пошла: писем — {0}, по одному раз в 20–40 с",
        ["Mail.Title"] = "РАССЫЛКА",
        ["Mail.Recipients"] = "ПОЛУЧАТЕЛИ",
        ["Mail.UseHintTip"] = "Нашли в профиле — сохранить в карточку и отправить",
        ["Mail.NewTemplate"] = "+ ШАБЛОН",
        ["Mail.DeleteTemplate"] = "УДАЛИТЬ",
        ["Mail.Subject"] = "Тема",
        ["Mail.Preview"] = "ПРЕДПРОСМОТР ДЛЯ",
        ["Mail.Send"] = "ОТПРАВИТЬ",
        ["Mail.Stop"] = "СТОП",
        ["Mail.SendBeat"] = "РАЗОСЛАТЬ",
        ["Mail.SendPicked"] = "РАЗОСЛАТЬ ОТМЕЧЕННЫМ",
        ["Settings.ReportProblem"] = "СООБЩИТЬ О ПРОБЛЕМЕ",
        ["Settings.ReportIntro"] = "Что случилось и что ты делал перед этим?",
        ["Settings.Interface"] = "ИНТЕРФЕЙС",
        ["Settings.Animations"] = "Анимации",
        ["Settings.AnimationsHint"] = "Окна плавно появляются и гаснут, результаты анализа выезжают по одному",
        ["Settings.AnimationsSystem"] = "В системе включено «Уменьшить движение» — анимации упрощены до затухания",
        ["Toast.Sent"] = "Отправлено ✓",
        ["Toast.Added"] = "{0} — добавлен в базу",
        ["Toast.AddedMany"] = "Добавлено артистов: {0}",
        ["Settings.Sounds"] = "Звуки",
        ["Settings.SoundsHint"] = "Тихие звуки на четыре события: анализ готов, бит отправлен, ★, парсер закончил",
        ["Settings.Logs"] = "ЛОГИ И ОТЛАДКА",
        ["Settings.EnableParserLogs"] = "Писать логи парсера",
        ["Settings.EnableDevTools"] = "Включить Avalonia DevTools (F12)",
        ["Settings.VerboseHttp"] = "Подробный лог HTTP",
        ["Settings.LogFile"] = "Файл лога",
        ["Settings.OpenFolder"] = "ОТКРЫТЬ ПАПКУ",

        // CRM и напоминания
        ["Crm.Title"] = "CRM",
        ["Crm.Empty"] = "Пометь артистам CRM-статус на вкладке АРТИСТЫ — они появятся здесь",
        ["Crm.MarkSent"] = "ОТМЕТИТЬ ОТПРАВЛЕННЫМ",
        ["Crm.Sent"] = "✓ отправлен",
        ["Crm.Pending"] = "⏳ ждёт отправки",
        ["Reminder.Title"] = "ПОРА ОТПРАВИТЬ",
        ["Reminder.Subtitle"] = "Эти биты привязаны, но ещё не отправлены",
        ["Reminder.OpenCrm"] = "ОТКРЫТЬ CRM",
        ["Reminder.Later"] = "ПОЗЖЕ",
    };
}
